name: job_posting_bidding_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.16.1
  page_transition: ^1.1.5
  cupertino_icons: ^0.1.2
  direct_select: ^1.0.0
  shimmer: ^1.0.1
  flutter_datetime_picker: ^1.3.5
  flutter_time_picker_spinner: ^1.0.6
  table_calendar: ^2.2.3
  badges: ^1.1.1
  dio: ^3.0.9
  path_provider: ^1.6.5
  intl: ^0.16.0
  pin_input_text_field: ^3.0.1
  dio_cookie_manager: ^1.0.0
  cached_network_image: ^2.0.0
  firebase_auth: ^0.15.5+3
  firebase_analytics: ^5.0.11
  shared_preferences: ^0.5.6+3
  swipe_button: ^0.0.2
  form_field_validator: ^1.0.1
  firebase_storage: ^3.1.5
  file_picker: ^1.6.0
  flutter_rating_bar: ^3.0.1+1
  google_map_location_picker: ^3.2.1+2
  latlong: ^0.6.1
  location: ^2.3.5
  geocoder: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-SemiBold.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Bold.ttf
  assets:
    - assets/images/top_right.svg
    - assets/images/bottom_left.svg
    - assets/images/menu.svg
    - assets/images/default_picture.png
  uses-material-design: true